### ISSUE TITLE
Beadandó

### ISSUE THREAD

**Issue by akosszanto** [Teaching-projects/januari-beadando-akosszanto#1]
Szép napot Tanár úr! Itt a beadandóm, mi a véleménye róla ?

**Comment by hegyhati** [comment]
Jo lesz ez nagyon, devan benne par logikatlan dolog, pl a 73-as sorban az if-et nem ertem, aztan azt sem, hogy miert van a lap_ertekek_asz, meg a sima lap_ertekek. 

Sokat tisztitana a dolgon, ha kiszervezned fuggvenyekbe a jatekos altali huzasokat, meg az oszto altali huzasokat.

a "foprogramod" valami ilyesmi lehetne:

```python
jatekos = jatekos_huz()
if jatekos == 21:
  print("Blackjack, nyertel")
elif jatekos > 21:
  print("Tulleptel, vesztettel.")
oszto = oszto_huz()
...
```

De pozitivum pl, hogy szepen megcsinaltad, hogy az asz az csak akkor er sokat, ha nem megyunk fole vele. 

Azt ugye nem kezeled, hogy egy kartyat most akar 6x is kihuzhatsz, de nem baj, ez belefer boven.

**Comment by akosszanto** [comment]
Szép napot  Tanár úr! megpróbáltam pár függvényt használni, illetve töröltem a 73-as sorban lévő if-et, a lap_ertekek_asz célja az, ha egymás után 2 ászt húzunk akkor a második ász értéke ne tudja meghaladni a 11-et, így ha két ászt húz egymás után mindenképp blackjack lesz és nem haladja túl.

**Comment by hegyhati** [comment]
Msot vannak teljesen identikus fuggvenyeid, amik redundansan teljesen ugyanazt csinaljak, de nem baj, legyen 5.
